### ISSUE TITLE
Выровнять с остальным кодом

### ISSUE THREAD

**Issue by Hibin** [DasGift/DasGift.github.io#2]
https://github.com/DasGift/DasGift.github.io/blob/d89e3ff5fd227e2fe7253f6ebe9e62902cb8b11c/JS%20in%20browser%20diplom/js/solution.js#L368

Выровнять с остальным кодом

**Comment by DasGift** [comment]
Не совсем пойму замечание..

**Comment by Hibin** [comment]
Съехало форматирование кода
https://github.com/DasGift/DasGift.github.io/blob/d89e3ff5fd227e2fe7253f6ebe9e62902cb8b11c/JS%20in%20browser%20diplom/js/solution.js#L366-L370

**Comment by DasGift** [comment]
Готово!
