### ISSUE TITLE
А его может не быть? Прокомментировать

### ISSUE THREAD

**Issue by Hibin** [DasGift/DasGift.github.io#4]
https://github.com/DasGift/DasGift.github.io/blob/d89e3ff5fd227e2fe7253f6ebe9e62902cb8b11c/JS%20in%20browser%20diplom/js/solution.js#L542-L544

Добавить комментарий, в каком случае может не быть. По коду это видно, но лучше расписать, чтобы не нужно было искать.

А еще лучше - смотреть следующий issue.

**Comment by DasGift** [comment]
Готово!
